name: Artifacts Challenge

on: [push]

jobs:
  artifact:
    name: upload artifact
    runs-on: ubuntu-latest
    steps:
        - name: Checkout steps
          uses: actions/checkout@v3
        - run: mkdir -p path/to/artifact

        - run: echo hello > path/to/artifact/${{ secrets.ARTIFACT_NAME }}

        - name: Upload Text file
          uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: path/to/artifact/${{ secrets.ARTIFACT_NAME }}
